name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js and dependencies
      run: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt-get install -y nodejs
        npm config set registry https://registry.npmjs.org/
        npm install

    - name: Build project
      run: npm run docusaurus build

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.HOST_SSH_KEY }}
        HOST_ADDRESS: ${{ secrets.HOST_ADDRESS }}
        HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        rsync -avz --delete ./build/* $HOST_USERNAME@$HOST_ADDRESS:/var/www/html/
